blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog', views.blog_list, name='blog_list'),
    path('my-post', views.user_post, name='user_post'),
    path('post-create', views.post_create, name='post_create'),
    path('post-detail/<slug:slug>/', views.post_detail, name='post_detail'),
    #path('post-detail/<int:id>/', views.post_detail, name='post_detail'),
    path('post-update/<slug:slug>/', views.post_update, name='post_update'),
    path('post-delete/<slug:slug>/', views.post_delete, name='post_delete'),
    path('post-search', views.post_search, name='post_search'),
    path('tinymce/', include('tinymce.urls')),
]

# -------------------class base view--------------------------
""""
    path('', IndexView.as_view(), name='home'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete')
"""

front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

madalali/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('tinymce/', include('tinymce.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),

    path('', include('front.urls', namespace='front')),
    path('', include('property.urls', namespace='property')),
    path('', include('blog.urls', namespace='blog')),

    path('user-profile/', user_views.user_profile, name='user_profile'),
    path('user-register/', user_views.user_register, name='user_register'),
    path('user-login/', auth_views.LoginView.as_view(
        template_name='accounts/user-login.html'), name='user_login'),
    path('logout', user_views.logout, name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # REST FRAMEWORK URLS
    path('api/blog/', include('blog.api.urls', namespace='blog_api')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('my-property', views.user_property, name='user_property'),
    path('property-search', views.search_list, name='property_search'),
    path('property-list', views.property_list, name='property_list'),
    path('property-detail/<slug:property_slug>',
         views.property_detail, name='property_detail'),

    #path('<slug:category_slug>' , views.productlist , name='product_list_category') ,
    #path('detail/<slug:product_slug>' , views.productdetail , name='product_detail'),


]

templates/partials/_alert.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
            {% else %}
            {{ message.tags|title }}
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/partials/_compare.html
<!-- Compare Properties Widget
    ================================================== -->
<div class="compare-slide-menu">

    <div class="csm-trigger"></div>

    <div class="csm-content">
        <h4>Compare Properties <div class="csm-mobile-trigger"></div>
        </h4>

        <div class="csm-properties">

            <!-- Property -->
            <div class="listing-item compact">
                <a href="single-property-page-2.html" class="listing-img-container">
                    <div class="remove-from-compare"><i class="fa fa-close"></i></div>
                    <div class="listing-badges">
                        <span>For Sale</span>
                    </div>
                    <div class="listing-img-content">
                        <span class="listing-compact-title">Eagle Apartments <i>$420,000</i></span>
                    </div>
                    <img src="images/listing-01.jpg" alt="">
                </a>
            </div>

            <!-- Property -->
            <div class="listing-item compact">
                <a href="single-property-page-2.html" class="listing-img-container">
                    <div class="remove-from-compare"><i class="fa fa-close"></i></div>
                    <div class="listing-badges">
                        <span>For Sale</span>
                    </div>
                    <div class="listing-img-content">
                        <span class="listing-compact-title">Selway Apartments <i>$420,000</i></span>
                    </div>
                    <img src="images/listing-03.jpg" alt="">
                </a>
            </div>

            <!-- Property -->
            <div class="listing-item compact">
                <a href="single-property-page-2.html" class="listing-img-container">
                    <div class="remove-from-compare"><i class="fa fa-close"></i></div>
                    <div class="listing-badges">
                        <span>For Sale</span>
                    </div>
                    <div class="listing-img-content">
                        <span class="listing-compact-title">Oak Tree Villas <i>$535,000</i></span>
                    </div>
                    <img src="images/listing-05.jpg" alt="">
                </a>
            </div>

        </div>

        <div class="csm-buttons">
            <a href="compare-properties.html" class="button">Compare</a>
            <a href="#" class="button reset">Reset</a>
        </div>
    </div>

</div>
<!-- Compare Properties Widget / End -->

templates/partials/_footer.html
<!-- Footer
================================================== -->
<div class="margin-top-55"></div>
<div id="footer" class="sticky-footer">
    <!-- Main -->
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-6">
                <img class="footer-logo" src="images/logo.png" alt="">
                <br><br>
                <p>Morbi convallis bibendum urna ut viverra. Maecenas quis consequat libero, a feugiat eros.
                    Nunc ut lacinia tortor morbi ultricies laoreet ullamcorper phasellus semper.</p>
            </div>

            <div class="col-md-4 col-sm-6 ">
                <h4>Helpful Links</h4>
                <ul class="footer-links">
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Sign Up</a></li>
                    <li><a href="#">My Account</a></li>
                    <li><a href="#">Add Property</a></li>
                    <li><a href="#">Pricing</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>

                <ul class="footer-links">
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Our Agents</a></li>
                    <li><a href="#">How It Works</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="col-md-3  col-sm-12">
                <h4>Contact Us</h4>
                <div class="text-widget">
                    <span>12345 Little Lonsdale St, Melbourne</span> <br>
                    Phone: <span>(123) 123-456 </span><br>
                    E-Mail:<span> <a href="#">office@example.com</a> </span><br>
                </div>

                <ul class="social-icons margin-top-20">
                    <li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
                    <li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
                    <li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
                    <li><a class="vimeo" href="#"><i class="icon-vimeo"></i></a></li>
                </ul>

            </div>

        </div>

        <!-- Copyright -->
        <div class="row">
            <div class="col-md-12">
                <div class="copyrights">© 2016 Findeo. All Rights Reserved.</div>
            </div>
        </div>

    </div>

</div>

templates/partials/_head.html
{% load staticfiles %}
<!DOCTYPE html>

<head>

    <!-- Basic Page Needs
    ================================================== -->

    {% if title %}
    <title>Madalali4u - {{ title }}</title>
    {% else %}
    <title>Madalali4u</title>
    {% endif %}


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/github.css' %}">

    <link rel="stylesheet" href="{% static 'dist/sweetalert2.css' %}">
    <link rel="stylesheet" href="{% static 'dist/sweetalert2.min.css' %}">
</head>

templates/partials/_headermenu.html
{% load static %}
<!-- Header Container
    ================================================== -->
<header id="header-container">

    <!-- Topbar -->
    <div id="top-bar">
        <div class="container">

            <!-- Left Side Content -->
            <div class="left-side">

                <!-- Top bar -->
                <ul class="top-bar-menu">
                    <li><i class="fa fa-phone"></i> (123) 123-456 </li>
                    <li><i class="fa fa-envelope"></i> <a href="#">office@example.com</a></li>
                    <li>
                        <div class="top-bar-dropdown">
                            <span>Dropdown Menu</span>
                            <ul class="options">
                                <li>
                                    <div class="arrow"></div>
                                </li>
                                <li><a href="#">Nice First Link</a></li>
                                <li><a href="#">Second Link With Long Title</a></li>
                                <li><a href="#">Third Link</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>

            </div>
            <!-- Left Side Content / End -->


            <!-- Left Side Content -->
            <div class="right-side">

                <!-- Social Icons -->
                <ul class="social-icons">
                    <li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
                    <li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
                    <li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
                    <li><a class="pinterest" href="#"><i class="icon-pinterest"></i></a></li>
                </ul>

            </div>
            <!-- Left Side Content / End -->

        </div>
    </div>
    <div class="clearfix"></div>
    <!-- Topbar / End -->


    <!-- Header -->
    <div id="header">
        <div class="container">

            <!-- Left Side Content -->
            <div class="left-side">

                <!-- Logo -->
                <div id="logo">
                    <a href="{% url 'front:index' %}"><img src="{% static 'images/logo.png' %}" alt=""></a>
                </div>


                <!-- Mobile Navigation -->
                <div class="mmenu-trigger">
                    <button class="hamburger hamburger--collapse" type="button">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>


                <!-- Main Navigation -->
                <nav id="navigation" class="style-1">
                    <ul id="responsive">


                        <li>
                            <a {% if '/' == request.path %} class="current" {% else %} href="{% url 'front:index' %}"
                                {% endif %}>
                                Home</a>
                        </li>

                        <li>
                            <a {% if 'about' in request.path %} class="current" {% else %}
                                href="{% url 'front:about' %}" {% endif %}>
                                About</a>
                        </li>

                        <li>
                            <a {% if 'property-list' in request.path %} class="current" {% else %}
                                href="{% url 'property:property_list' %}" {% endif %}>
                                Listings</a>
                        </li>


                        <li>
                            <a {% if 'blog' in request.path %} class="current" {% else %}
                                href="{% url 'blog:blog_list' %}" {% endif %}>
                                Blog</a>
                        </li>

                        <li>
                            <a {% if 'contact' in request.path %} class="current" {% else %}
                                href="{% url 'front:contact' %}" {% endif %}>
                                Contact Us</a>
                        </li>


                    </ul>
                </nav>
                <div class="clearfix"></div>
                <!-- Main Navigation / End -->

            </div>
            <!-- Left Side Content / End -->

            <!-- Right Side Content / End -->
            <div class="right-side">
                <!-- Header Widget -->
                <div class="header-widget">

                    {% if user.is_authenticated %}
                    <!-- User Menu -->
                    <div class="user-menu">
                        <div class="user-name"><span><img src="{{user.profile.image.url}}" alt="profile"></span>Hi,
                            {{user.username}}!
                        </div>
                        <ul>
                            <li><a href=" {% url 'user_profile' %}"><i class="sl sl-icon-user"></i> My Profile</a></li>
                            <li><a href="my-bookmarks.html"><i class="sl sl-icon-star"></i> Bookmarks</a></li>
                            <li><a href="my-properties.html"><i class="sl sl-icon-docs"></i> My Properties</a></li>

                            <li>
                                <a href="javascript:{document.getElementById('logout').submit()}">
                                    <i class="sl sl-icon-power"></i> Log Out</a>
                                </a>
                                <form action="{% url 'logout' %}" method="POST" id="logout">
                                    {% csrf_token %}
                                    <input type="hidden">
                                </form>
                            </li>

                        </ul>
                    </div>
                    <a href="" class="button border">Submit Property</a>

                    {% else %}
                    <a href="login-register.html" class="sign-in"> FOR RENT </a><a href="login-register.html"
                        class="sign-in">FOR SALE</a>
                    <a href="{% url 'user_login' %}" class="button border">Submit Property</a>
                    {% endif %}
                </div>
                <!-- Header Widget / End -->
            </div>
            <!-- Right Side Content / End -->

        </div>
    </div>
    <!-- Header / End -->

</header>
<div class="clearfix"></div>
<!-- Header Container / End -->

templates/partials/_message_alert.html
{% if messages %}
{% for message in  messages %}

<div class="notification {{ message.tags }} closeable">
    <p><span>{{ message.tags }}!</span> {{ message }}.</p>
    <a class="close"></a>
</div>

{% endfor %}
{% endif %}

templates/partials/_script.html
{% load static %}
<!-- Scripts
================================================== -->
<script type="text/javascript" src="{% static 'scripts/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/jquery-migrate-3.1.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/chosen.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/rangeSlider.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/sticky-kit.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/masonry.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/mmenu.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/tooltips.min.js' %}"></script>




<script type="text/javascript" src="{% static 'scripts/custom.js' %}"></script>


<!-- Maps -->
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
<script type="text/javascript" src="{% static 'scripts/infobox.min.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/markerclusterer.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/maps.js' %}"></script>

<!-- Tiny MCE -->
<script type="text/javascript" src="{% static 'scripts/highlight.pack.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>


<!-- Sweet Alert -->
<script type="text/javascript" src="{% static 'dist/sweetalert2.all.js' %}"></script>
<script type="text/javascript" src="{% static 'dist/sweetalert2.all.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dist/sweetalert2.js' %}"></script>
<script type="text/javascript" src="{% static 'dist/sweetalert2.min.js' %}"></script>




<!-- Date Range Picker - docs: http://www.daterangepicker.com/ -->
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/daterangepicker.js' %}"></script>
<script>
    // Calendar Init
    $(function () {
        $('#date-picker').daterangepicker({
            "opens": "left",
            singleDatePicker: true,

            // Disabling Date Ranges
            isInvalidDate: function (date) {
                // Disabling Date Range
                var disabled_start = moment('09/02/2018', 'MM/DD/YYYY');
                var disabled_end = moment('09/06/2018', 'MM/DD/YYYY');
                return date.isAfter(disabled_start) && date.isBefore(disabled_end);

                // Disabling Single Day
                // if (date.format('MM/DD/YYYY') == '08/08/2018') {
                //     return true; 
                // }
            }
        });
    });

    // Calendar animation
    $('#date-picker').on('showCalendar.daterangepicker', function (ev, picker) {
        $('.daterangepicker').addClass('calendar-animated');
    });
    $('#date-picker').on('show.daterangepicker', function (ev, picker) {
        $('.daterangepicker').addClass('calendar-visible');
        $('.daterangepicker').removeClass('calendar-hidden');
    });
    $('#date-picker').on('hide.daterangepicker', function (ev, picker) {
        $('.daterangepicker').removeClass('calendar-visible');
        $('.daterangepicker').addClass('calendar-hidden');
    });
</script>


<!-- Replacing dropdown placeholder with selected time slot -->
<script>
    $(".time-slot").each(function () {
        var timeSlot = $(this);
        $(this).find('input').on('change', function () {
            var timeSlotVal = timeSlot.find('strong').text();

            $('.panel-dropdown.time-slots-dropdown a').html(timeSlotVal);
            $('.panel-dropdown').removeClass('active');
        });
    });
</script>



<!-- Google Autocomplete -->
<script>
    function initAutocomplete() {
        var input = document.getElementById('autocomplete-input');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.addListener('place_changed', function () {
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                window.alert("No details available for input: '" + place.name + "'");
                return;
            }
        });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete"></script>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>-->

{% load sweetify %}
{% sweetify %}