blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog', views.blog_list, name='blog_list'),
    path('my-post', views.user_post, name='user_post'),
    path('post-create', views.post_create, name='post_create'),
    path('post-detail/<slug:slug>/', views.post_detail, name='post_detail'),
    #path('post-detail/<int:id>/', views.post_detail, name='post_detail'),
    path('post-update/<slug:slug>/', views.post_update, name='post_update'),
    path('post-delete/<slug:slug>/', views.post_delete, name='post_delete'),
    path('post-search', views.post_search, name='post_search'),
    path('tinymce/', include('tinymce.urls')),
]

# -------------------class base view--------------------------
""""
    path('', IndexView.as_view(), name='home'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete')
"""

madalali/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('tinymce/', include('tinymce.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),

    path('', include('front.urls', namespace='front')),
    path('', include('property.urls', namespace='property')),
    path('', include('blog.urls', namespace='blog')),

    path('user-profile/', user_views.user_profile, name='user_profile'),
    path('user-register/', user_views.user_register, name='user_register'),
    path('user-login/', auth_views.LoginView.as_view(
        template_name='accounts/user-login.html'), name='user_login'),
    path('logout', user_views.logout, name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # REST FRAMEWORK URLS
    path('api/blog/', include('blog.api.urls', namespace='blog_api')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('my-property', views.user_property, name='user_property'),
    path('property-search', views.search_list, name='property_search'),
    path('property-list', views.property_list, name='property_list'),
    path('property-detail/<slug:property_slug>',
         views.property_detail, name='property_detail'),

    #path('<slug:category_slug>' , views.productlist , name='product_list_category') ,
    #path('detail/<slug:product_slug>' , views.productdetail , name='product_detail'),


]

property/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from datetime import datetime
from realtor.models import Realtor
from django.urls import reverse
from autoslug import AutoSlugField


# Create your models here.
PROPERTY_CATEGORY = (

    ("Lands", "Lands"),
    ("Apartments", "Apartments"),
    ("Commercials", "Commercials"),
    ("Vehicles", "Vehicles"),

)

PROPERTY_SUB_CATEGORY = (
    ("Plot", "Plot"),
    ("Farm", "Farm"),
    ("Apartment", "Apartment"),
    ("House", "House"),
    ("Room", "Room"),
    ("Hostel", "Hostel"),
    ("Office Place", "Office Place"),
    ("Frame", "Frame"),
    ("Car", "Car"),
    ("Motorcycle", "Motorcycle"),
    ("Bajaji", "Bajaji"),
)


PROPERTY_TYPE = (
    ("For Rent", "For Rent"),
    ("For Sale", "For Sale"),
)


class Property(models.Model):

    # contain all the proprties informations
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    district = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=500)
    property_type = models.CharField(max_length=501, choices=PROPERTY_TYPE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    bedrooms = models.IntegerField(blank=True)
    rooms = models.IntegerField(blank=True)
    bathrooms = models.IntegerField(blank=True)
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, null=True)
    photo_main = models.ImageField(
        upload_to='main_photo/%Y/%m/%d/', blank=True, null=True)
    #created = models.DateTimeField(default=timezone.now)
    is_published = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    created = models.DateTimeField(default=datetime.now)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Property, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = 'Properties'

    def __str__(self):
        return self.title


class PropertyImages(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to='property/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.image.name

    class Meta:
        verbose_name = 'Property Image'
        verbose_name_plural = 'Property Images'


class Category(models.Model):
    category_name = models.CharField(max_length=50, choices=PROPERTY_CATEGORY)
    slug = AutoSlugField(populate_from='category_name', null=True)
    #image = models.ImageField(upload_to='category/', blank=True, null=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name


class SubCategory(models.Model):
    title = models.CharField(max_length=50, choices=PROPERTY_SUB_CATEGORY)
    slug = AutoSlugField(populate_from='title', null=True)
    created = models.DateTimeField(default=datetime.now)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'sub category'
        verbose_name_plural = 'sub categories'

    def __str__(self):
        return self.title

property/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.contrib import messages


from .models import Property, PropertyImages, Category
from .choices import bedroom_choices, bathroom_choices, status_choices, type_choices, room_choices


# Create your views here.

def is_valid_queryparam(param):
    return param != '' and param is not None


""" FILTER FUNCTION FOR SEARCHINGLISTING PROPERTIS """


def filter(request):
    qs = Property.objects.all()
    tab1 = request.GET.get('tab') == 'Any Status'
    tab2 = request.GET.get('tab') == 'For Sale'
    tab3 = request.GET.get('tab') == 'For Rent'

    status = request.GET.get('status')
    keyword = request.GET.get('keyword')
    category = request.GET.get('category')
    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    area_min = request.GET.get('area_min')
    area_max = request.GET.get('area_max')
    bed = request.GET.get('bed')
    bath = request.GET.get('bath')
    room = request.GET.get('room')

    # not_reviewed = request.GET.get('notReviewed')

    if is_valid_queryparam(status) and status != 'Any Status':
        qs = qs.filter(property_type__contains=status)

    if is_valid_queryparam(keyword):
        qs = qs.filter(
            Q(address__icontains=keyword) |
            Q(title__icontains=keyword) |
            Q(description__icontains=keyword) |
            Q(realtor__first_name__icontains=keyword)
        ).distinct()

    if is_valid_queryparam(category) and category != 'Any Type':
        qs = qs.filter(category__category_name=category)

    if is_valid_queryparam(price_min):
        qs = qs.filter(price__gte=price_min)

    if is_valid_queryparam(price_max):
        qs = qs.filter(price__lt=price_max)

    if is_valid_queryparam(area_min):
        qs = qs.filter(sqft__gte=area_min)

    if is_valid_queryparam(area_max):
        qs = qs.filter(sqft__lt=area_max)

    if is_valid_queryparam(bed) and bed != 'Beds(Any)':
        qs = qs.filter(bedrooms__contains=bed)

    if is_valid_queryparam(bath) and bed != 'Baths (Any)':
        qs = qs.filter(bathrooms__contains=bath)

    if is_valid_queryparam(room) and room != 'Rooms (Any)':
        qs = qs.filter(rooms__contains=room)

    if tab1 == 'on':
        qs = qs.filter(property_type=tab1)

    elif tab2 == 'on':
        qs = qs.filter(property_type=tab2)

    elif tab3 == 'on':
        qs = qs.filter(property_type=tab3)

    """
    if reviewed == 'on':
        qs = qs.filter(reviewed=True)

    elif not_reviewed == 'on':
        qs = qs.filter(reviewed=False)
    """
    return qs


""" SEARCH LIST FUNCTION FOR LISTING PROPERTIS """


def search_list(request):
   # category = None
    propertytlist = filter(request)
    paginator = Paginator(propertytlist, 2)  # Show 25 contacts per page
    page = request.GET.get('page')

    propertytlist = paginator.get_page(page)

    template = 'property/search-list.html'
    context = {
        'property_list': propertytlist,
        'bedroom_choices': bedroom_choices,
        'bathroom_choices': bathroom_choices,
        'status_choices': status_choices,
        'type_choices': type_choices,
        'room_choices': room_choices,
    }
    return render(request, template, context)


""" PROPERTY LIST FUNCTION FOR LISTING PROPERTIS """


def property_list(request):

    # category = None

    propertytlist = Property.objects.all()
    featured_list = Property.objects.filter(
        featured=True).order_by('-featured')[:4]
    latest_list = Property.objects.order_by('-created')[:8]
    # propertyimages = PropertyImages.objects.filter(property=propertytlist)
    """
    categorylist = Category.objects.annotate(total_projects=Count('project'))

    if category_slug :
        category = get_object_or_404(Category ,slug=category_slug)
        projectlist = projectlist.filter(category=category)
    """

    paginator = Paginator(propertytlist, 2)  # Show 25 contacts per page
    page = request.GET.get('page')

    propertytlist = paginator.get_page(page)

    template = 'property/property-list.html'
    context = {'property_list': propertytlist}

    # context = {'project_list' : projectlist , 'category_list' : categorylist ,'category' : category }
    return render(request, template, context)


def property_detail(request, property_slug):
    print(property_slug)
    propertydetail = Property.objects.get(slug=property_slug)
    propertyimages = PropertyImages.objects.filter(property=propertydetail)
    template = 'property/property-detail.html'
    context = {'property_detail': propertydetail,
               'property_images': propertyimages}
    return render(request, template, context)


def user_property(request):

    propertytlist = Property.objects.all()
    # propertyimages = PropertyImages.objects.filter(property=propertytlist)
    """
        categorylist = Category.objects.annotate(total_projects=Count('project'))

        if category_slug :
            category = get_object_or_404(Category ,slug=category_slug)
            projectlist = projectlist.filter(category=category)
        """

    paginator = Paginator(propertytlist, 2)  # Show 25 contacts per page
    page = request.GET.get('page')

    propertytlist = paginator.get_page(page)

    template = 'accounts/my-property.html'
    context = {'property_list': propertytlist}

    # context = {'project_list' : projectlist , 'category_list' : categorylist ,'category' : category }
    return render(request, template, context)

property/templates/property/property-list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- Titlebar
================================================== -->
<div class="parallax titlebar" data-background="images/listings-parallax.jpg" data-color="#333333"
	data-color-opacity="0.7" data-img-width="800" data-img-height="505">

	<div id="titlebar">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<h2>Listings</h2>
					<span>Grid Layout With Sidebar</span>

					<!-- Breadcrumbs -->
					<nav id="breadcrumbs">
						<ul>
							<li><a href="#">Home</a></li>
							<li>Listings</li>
						</ul>
					</nav>

				</div>
			</div>
		</div>
	</div>
</div>



<!-- Content
================================================== -->
<div class="container">
	<div class="row fullwidth-layout">

		<div class="col-md-12">

			<!-- Sorting / Layout Switcher -->
			<div class="row margin-bottom-15">

				<div class="col-md-6">
					<!-- Sort by -->
					<div class="sort-by">
						<label>Sort by:</label>

						<div class="sort-by-select">
							<select data-placeholder="Default order" class="chosen-select-no-single">
								<option>Default Order</option>
								<option>Price Low to High</option>
								<option>Price High to Low</option>
								<option>Newest Properties</option>
								<option>Oldest Properties</option>
							</select>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<!-- Layout Switcher -->
					<div class="layout-switcher">
						<a href="#" class="list"><i class="fa fa-th-list"></i></a>
						<a href="#" class="grid"><i class="fa fa-th-large"></i></a>
						<a href="#" class="grid-three"><i class="fa fa-th"></i></a>
					</div>
				</div>
			</div>


			<!-- Listings -->
			<div class="listings-container list-layout">
				{% if property_list %}
				{% for property in property_list %}
				<!-- Listing Item -->
				<div class="listing-item">

					<a href="{% url 'property:property_detail' property.slug %}" class="listing-img-container">

						<div class="listing-badges">
							<span class="featured">Featured</span>
							<span>{{property.property_type}}</span>
						</div>

						<div class="listing-img-content">
							<span class="listing-price">$ {{property.price | intcomma}}</span>
							<span class="like-icon with-tip" data-tip-content="Add to Bookmarks"></span>
							<span class="compare-button with-tip" data-tip-content="Add to Compare"></span>
						</div>

						<div class="listing-carousel">

							<div><img src="{{property.photo_main.url}}" alt=""></div>
							<div><img src="images/listing-01b.jpg" alt=""></div>
							<div><img src="images/listing-01c.jpg" alt=""></div>

						</div>
					</a>



					<div class="listing-content">

						<div class="listing-title">
							<h4><a href="{% url 'property:property_detail' property.slug %}"> {{property.title}}</a>
							</h4>
							<a href="https://maps.google.com/maps?q=221B+Baker+Street,+London,+United+Kingdom&hl=en&t=v&hnear=221B+Baker+St,+London+NW1+6XE,+United+Kingdom"
								class="listing-address popup-gmaps">
								<i class="fa fa-map-marker"></i>
								{{property.address}}
							</a>

							<a href="{% url 'property:property_detail' property.slug %}"
								class="details button border">Details</a>
						</div>

						<ul class="listing-details">
							<li>{{property.sqft}} sq ft</li>
							<li>{{property.rooms}} Bedroom</li>
							<li>{{property.bedrooms}} Rooms</li>
							<li>{{property.bathrooms}} Bathroom</li>
						</ul>

						<div class="listing-footer">
							<a href="#"><i class="fa fa-user"></i> {{property.realtor.first_name}}
								{{property.realtor.last_name}}</a>
							<span><i class="fa fa-calendar-o"></i> {{property.created | naturaltime}}</span>
						</div>

					</div>

				</div>
				<!-- Listing Item / End -->
				{% endfor %}
				{% else %}
				<div cclass="listing-item">
					<p>No Listings Avaialable yet</p>
				</div>
				{% endif %}


			</div>
			<!-- Listings Container / End -->

			<div class="clearfix"></div>

			{% if property_list.has_other_pages %}
			<!-- Pagination -->
			<div class="pagination-container margin-top-20">


				<nav class="pagination">
					<ul>
						{% for i in property_list.paginator.page_range %}
						{% if property_list.number == i %}
						<li><a class="current-page">{{i}}</a></li>
						{% else %}
						<li><a href="?page={{i}}">{{i}}</a></li>
						{% comment %}
						<li class="blank">...</li>
						<li><a href="?page={{i.previous_page_number }}">22</a></li>
						{% endcomment %}
						{% endif %}
						{% endfor %}
					</ul>
				</nav>



				<nav class="pagination-next-prev">
					<ul>
						{% if property_list.has_previous %}
						<li><a href="?page={{ property_list.previous_page_number }}" class="prev">Previous</a></li>
						{% else %}
						<li class="disabled"></li>
						{% endif %}

						{% if property_list.has_next %}
						<li><a href="?page={{ property_list.next_page_number }}" class="next">Next</a></li>
						{% else %}
						<li class="disabled"></li>
						{% endif %}
					</ul>
				</nav>
			</div>
			<!-- Pagination / End -->
			{% endif %}

		</div>

	</div>
</div>


{% endblock %}

property/templates/property/search-list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}


<!-- Search
================================================== -->
<section class="search margin-bottom-50">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<!-- Title -->
				<h3 class="search-title">Search</h3>

				<!-- Main Search -->
				<form method="GET" action="{% url 'property:property_search' %}">

					<!-- Form -->
					<div class="main-search-box no-shadow">


						<!-- Row With Forms -->
						<div class="row with-forms">

							<!-- Status -->
							<div class="col-md-3">
								<select data-placeholder="Any Status" class="chosen-select-no-single" name="status">
									<option>Any Status</option>
									{% for key,value in status_choices.items %}
									<option value="{{ key }}">{{ value }}</option>
									{% endfor %}>
								</select>
							</div>

							<!-- Property Type -->
							<div class="col-md-3">
								<select data-placeholder="Any Type" class="chosen-select-no-single" name="category">
									<option>Any Type</option>
									{% for key,value in type_choices.items %}
									<option value="{{ key }}">{{ value }}</option>
									{% endfor %}>
								</select>
							</div>

							<!-- Main Search Input -->
							<div class="col-md-6">
								<div class="main-search-input">
									<input type="text" placeholder="Enter address e.g. street, city or state" value=""
										name="keyword" />
									<button class="button">Search</button>
								</div>
							</div>

						</div>
						<!-- Row With Forms / End -->


						<!-- Row With Forms -->
						<div class="row with-forms">

							<!-- Min Area-->
							<div class="col-md-3">


								<!-- Select Input -->
								<div class="select-input">
									<input type="text" placeholder="Min Area" data-unit="Sq Ft" name="area_min">
								</div>
								<!-- Select Input / End -->


							</div>

							<!-- Max Area -->
							<div class="col-md-3">

								<!-- Select Input -->
								<div class="select-input">
									<input type="text" placeholder="Max Area" data-unit="Sq Ft" name="area_max">
								</div>
								<!-- Select Input / End -->

							</div>


							<!-- Min Price -->
							<div class="col-md-3">

								<!-- Select Input -->
								<div class="select-input">
									<input type="text" placeholder="Min Price" data-unit="USD" name="price_min">
								</div>
								<!-- Select Input / End -->
							</div>


							<!-- Max Price -->
							<div class="col-md-3">

								<!-- Select Input -->
								<div class="select-input">
									<input type="text" placeholder="Max Price" data-unit="USD" name="price_max">
								</div>
								<!-- Select Input / End -->

							</div>

						</div>
						<!-- Row With Forms / End -->


						<!-- More Search Options -->
						<a href="#" class="more-search-options-trigger margin-top-10" data-open-title="More Options"
							data-close-title="Less Options"></a>

						<div class="more-search-options relative">
							<div class="more-search-options-container">

								<!-- Row With Forms -->
								<div class="row with-forms">

									<!-- Age of Home -->
									<div class="col-md-3">
										<select data-placeholder="Age of Home" class="chosen-select-no-single">
											<option label="blank"></option>
											<option>Age of Home (Any)</option>
											<option>0 - 1 Years</option>
											<option>0 - 5 Years</option>
											<option>0 - 10 Years</option>
											<option>0 - 20 Years</option>
											<option>0 - 50 Years</option>
											<option>50 + Years</option>
										</select>
									</div>

									<!-- Rooms Area -->
									<div class="col-md-3">
										<select data-placeholder="Rooms" class="chosen-select-no-single" name="room">
											<option label="blank"></option>
											<option>Rooms (Any)</option>
											{% for key,value in room_choices.items %}
											<option value="{{ key }}">{{ value }}</option>
											{% endfor %}
										</select>
									</div>

									<!-- Beds -->
									<div class="col-md-3">
										<select data-placeholder="Beds" class="chosen-select-no-single" name="bed">
											<option label="blank"></option>
											<option>Beds (Any)</option>
											{% for key,value in bedroom_choices.items %}
											<option value="{{ key }}">{{ value }}</option>
											{% endfor %}
										</select>
									</div>

									<!-- baths-->
									<div class="col-md-3">
										<select data-placeholder="Baths" class="chosen-select-no-single" name="bath">
											<option label="blank"></option>
											<option>Baths (Any)</option>
											{% for key,value in bathroom_choices.items %}
											<option value="{{ key }}">{{ value }}</option>
											{% endfor %}
										</select>
									</div>

								</div>
								<!-- Row With Forms / End -->

							</div>

						</div>
						<!-- More Search Options / End -->


					</div>
					<!-- Box / End -->
				</form>
			</div>
		</div>
	</div>
</section>

<!-- Content
================================================== -->
<div class="container">
	<div class="row fullwidth-layout">

		<div class="col-md-12">

			<!-- Sorting / Layout Switcher -->
			<div class="row margin-bottom-15">

				<div class="col-md-6">
					<!-- Sort by -->
					<div class="sort-by">
						<label>Sort by:</label>

						<div class="sort-by-select">
							<select data-placeholder="Default order" class="chosen-select-no-single">
								<option>Default Order</option>
								<option>Price Low to High</option>
								<option>Price High to Low</option>
								<option>Newest Properties</option>
								<option>Oldest Properties</option>
							</select>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<!-- Layout Switcher -->
					<div class="layout-switcher">
						<a href="#" class="grid-three"><i class="fa fa-th"></i></a>

						<a href="#" class="grid"><i class="fa fa-th-large"></i></a>
						<a href="#" class="list"><i class="fa fa-th-list"></i></a>

					</div>
				</div>
			</div>


			<!-- Listings -->
			<div class="listings-container grid-layout-three">
				{% if property_list %}
				{% for property in property_list %}
				<!-- Listing Item -->
				<div class="listing-item">

					<a href="{% url 'property:property_detail' property.slug %}" class="listing-img-container">

						<div class="listing-badges">
							<span class="featured">Featured</span>
							<span>{{property.property_type}}</span>
						</div>

						<div class="listing-img-content">
							<span class="listing-price">$ {{property.price | intcomma}}</span>
							<span class="like-icon with-tip" data-tip-content="Add to Bookmarks"></span>
							<span class="compare-button with-tip" data-tip-content="Add to Compare"></span>
						</div>

						<div class="listing-carousel">

							<div><img src="{{property.photo_main.url}}" alt=""></div>
							<div><img src="images/listing-01b.jpg" alt=""></div>
							<div><img src="images/listing-01c.jpg" alt=""></div>

						</div>
					</a>



					<div class="listing-content">

						<div class="listing-title">
							<h4><a href="{% url 'property:property_detail' property.slug %}"> {{property.title}}</a>
							</h4>
							<a href="https://maps.google.com/maps?q=221B+Baker+Street,+London,+United+Kingdom&hl=en&t=v&hnear=221B+Baker+St,+London+NW1+6XE,+United+Kingdom"
								class="listing-address popup-gmaps">
								<i class="fa fa-map-marker"></i>
								{{property.address}}
							</a>

							<a href="{% url 'property:property_detail' property.slug %}"
								class="details button border">Details</a>
						</div>

						<ul class="listing-details">
							<li>{{property.sqft}} sq ft</li>
							<li>{{property.rooms}} Bedroom</li>
							<li>{{property.bedrooms}} Rooms</li>
							<li>{{property.bathrooms}} Bathroom</li>
						</ul>

						<div class="listing-footer">
							<a href="#"><i class="fa fa-user"></i> {{property.realtor.first_name}}
								{{property.realtor.last_name}}</a>
							<span><i class="fa fa-calendar-o"></i> {{property.created | naturaltime}}</span>
						</div>

					</div>

				</div>
				<!-- Listing Item / End -->
				{% endfor %}
				{% else %}
				<div cclass="listing-item">
					<p aligin="center">No Listings Avaialable</p>
				</div>
				{% endif %}


			</div>
			<!-- Listings Container / End -->

			<div class="clearfix"></div>

			{% if property_list.has_other_pages %}
			<!-- Pagination -->
			<div class="pagination-container margin-top-20">


				<nav class="pagination">
					<ul>
						{% for i in property_list.paginator.page_range %}
						{% if property_list.number == i %}
						<li><a class="current-page">{{i}}</a></li>
						{% else %}
						<li><a href="?page={{i}}">{{i}}</a></li>
						{% comment %}
						<li class="blank">...</li>
						<li><a href="?page={{i.previous_page_number }}">22</a></li>
						{% endcomment %}
						{% endif %}
						{% endfor %}
					</ul>
				</nav>



				<nav class="pagination-next-prev">
					<ul>
						{% if property_list.has_previous %}
						<li><a href="?page={{ property_list.previous_page_number }}" class="prev">Previous</a></li>
						{% else %}
						<li class="disabled"></li>
						{% endif %}

						{% if property_list.has_next %}
						<li><a href="?page={{ property_list.next_page_number }}" class="next">Next</a></li>
						{% else %}
						<li class="disabled"></li>
						{% endif %}
					</ul>
				</nav>
			</div>
			<!-- Pagination / End -->
			{% endif %}

		</div>

	</div>
</div>


{% endblock %}