blog/api/urls.py
from blog.api.views import(
    api_detail_blog_view,
    api_update_blog_view,
    api_delete_blog_view,
    api_create_blog_view,
    PostListApiView,
    # api_is_author_of_blogpost,
    # ApiBlogListView
)
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('detail/<id>', api_detail_blog_view, name="detail"),
    path('update/<id>', api_update_blog_view, name="update"),
    path('delete/<id>', api_delete_blog_view, name="delete"),
    path('create', api_create_blog_view, name="create"),
    path('blog-list', PostListApiView.as_view(), name="blog_list"),
    #path('list', ApiBlogListView.as_view(), name="list"),
    #path('<slug>/is_author', api_is_author_of_blogpost, name="is_author"),
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog', views.blog_list, name='blog_list'),
    path('my-post', views.user_post, name='user_post'),
    path('post-create', views.post_create, name='post_create'),
    path('post-detail/<slug:slug>/', views.post_detail, name='post_detail'),
    #path('post-detail/<int:id>/', views.post_detail, name='post_detail'),
    path('post-update/<slug:slug>/', views.post_update, name='post_update'),
    path('post-delete/<slug:slug>/', views.post_delete, name='post_delete'),
    path('post-search', views.post_search, name='post_search'),
    path('tinymce/', include('tinymce.urls')),
]

# -------------------class base view--------------------------
""""
    path('', IndexView.as_view(), name='home'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete')
"""

front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

madalali/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('tinymce/', include('tinymce.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),

    path('', include('front.urls', namespace='front')),
    path('', include('property.urls', namespace='property')),
    path('', include('blog.urls', namespace='blog')),

    path('user-profile/', user_views.user_profile, name='user_profile'),
    path('user-register/', user_views.user_register, name='user_register'),
    path('user-login/', auth_views.LoginView.as_view(
        template_name='accounts/user-login.html'), name='user_login'),
    path('logout', user_views.logout, name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # REST FRAMEWORK URLS
    path('api/blog/', include('blog.api.urls', namespace='blog_api')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('my-property', views.user_property, name='user_property'),
    path('property-search', views.search_list, name='property_search'),
    path('property-list', views.property_list, name='property_list'),
    path('property-detail/<slug:property_slug>',
         views.property_detail, name='property_detail'),

    #path('<slug:category_slug>' , views.productlist , name='product_list_category') ,
    #path('detail/<slug:product_slug>' , views.productdetail , name='product_detail'),


]

blog/models.py
from tinymce.models import HTMLField
from django.utils import timezone
from django.utils.text import slugify
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from autoslug import AutoSlugField

User = get_user_model()


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class PostView(models.Model):
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40)
    created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.user.username


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    profile_picture = models.ImageField(
        upload_to='blog/', blank=True, null=True)
    about_author = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    #slug = AutoSlugField(populate_from='title', blank=True)
    slug = models.SlugField(blank=True, null=True)
    overview = models.TextField()
    timestamp = models.DateTimeField(default=datetime.now)
    #updated_on = models.DateTimeField(default=datetime.now)
    status = models.IntegerField(choices=STATUS, default=0)

    #timestamp = models.DateTimeField(auto_now_add=True)
    content = HTMLField()
    #comment_count = models.IntegerField(default=0)
    #view_count = models.IntegerField(default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='blog/', blank=True, null=True)
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField(default=False)
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('blog:post_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('blog:post_delete', kwargs={'slug': self.slug})

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()


""" SIGN UP MODEL FOR EMAILSUBSCRIBTION"""


class Signup(models.Model):
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail',
                  'categories', 'featured', 'previous_post', 'next_post')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Type your comment',
        'id': 'comment',
        'rows': '3',
        'cols': '40'
    }))

    class Meta:
        model = Comment
        fields = ('content', )

blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.exceptions import ParseError
from PIL import Image
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.filters import SearchFilter, OrderingFilter

from blog.models import Post
from blog.api.serializers import BlogPostSerializer
from blog.models import Author
# from blog.api.serializers import BlogPostSerializer, BlogPostUpdateSerializer, BlogPostCreateSerializer

SUCCESS = 'success'
ERROR = 'error'
DELETE_SUCCESS = 'deleted'
UPDATE_SUCCESS = 'updated'
CREATE_SUCCESS = 'created'


class PostListApiView(APIView):

    serializer_class = BlogPostSerializer

    def get(self, request):
        try:
            blog_list = Post.objects.all()
            serializer = BlogPostSerializer(
                blog_list, context={'request': request}, many=True)
            return Response(serializer.data)

        except ValueError as e:
            return Response(e.args[0], status.HTTP_400_BAD_REQUEST)


# Response: https://gist.github.com/mitchtabian/93f287bd1370e7a1ad3c9588b0b22e3d
# Url: https://<your-domain>/api/blog/<slug>/
# Headers: Authorization: Token <token>
@api_view(['GET', ])
# @permission_classes((IsAuthenticated, ))
def api_detail_blog_view(request, id):

    try:
        blog_post = Post.objects.get(id=id)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = BlogPostSerializer(blog_post)
        return Response(serializer.data)

# Response: https://gist.github.com/mitchtabian/32507e93c530aa5949bc08d795ba66df
# Url: https://<your-domain>/api/blog/<slug>/update
# Headers: Authorization: Token <token>
@api_view(['PUT', ])
# @permission_classes((IsAuthenticated,))
def api_update_blog_view(request, id):

    try:
        blog_post = Post.objects.get(id=id)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    # user = request.user
    # if blog_post.author != user:
    #	return Response({'response':"You don't have permission to edit that."})

    if request.method == 'PUT':
        # serializer = BlogPostUpdateSerializer(blog_post, data=request.data, partial=True)
        serializer = BlogPostSerializer(
            blog_post, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data['response'] = UPDATE_SUCCESS
            # data['pk'] = blog_post.pk
            # data['title'] = blog_post.title
            # data['body'] = blog_post.body
            # data['slug'] = blog_post.slug
            # data['date_updated'] = blog_post.date_updated
            # image_url = str(request.build_absolute_uri(blog_post.image.url))
            # if "?" in image_url:
            #	image_url = image_url[:image_url.rfind("?")]
            # data['image'] = image_url
            # data['username'] = blog_post.author.username
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


"""
@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_is_author_of_blogpost(request, slug):
	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	data = {}
	user = request.user
	if blog_post.author != user:
		data['response'] = "You don't have permission to edit that."
		return Response(data=data)
	data['response'] = "You have permission to edit that."
	return Response(data=data)
"""

# Response: https://gist.github.com/mitchtabian/a97be3f8b71c75d588e23b414898ae5c
# Url: https://<your-domain>/api/blog/<slug>/delete
# Headers: Authorization: Token <token>
@api_view(['DELETE', ])
# @permission_classes((IsAuthenticated, ))
def api_delete_blog_view(request, id):

    try:
        blog_post = Post.objects.get(id=id)
    except Post.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    # user = request.user
    # if blog_post.author != user:
    #	return Response({'response':"You don't have permission to delete that."})

    if request.method == 'DELETE':
        operation = blog_post.delete()
        data = {}
        if operation:
            data['response'] = DELETE_SUCCESS
        return Response(data=data)


# Response: https://gist.github.com/mitchtabian/78d7dcbeab4135c055ff6422238a31f9
# Url: https://<your-domain>/api/blog/create
# Headers: Authorization: Token <token>
@api_view(['POST'])
# @permission_classes((IsAuthenticated,))
def api_create_blog_view(request):

    account = Author.objects.get(pk=1)
    blog_post = Post(author=account)
    if request.method == 'POST':

        # data = request.data
        # data['author'] = request.user.pk
        # serializer = BlogPostCreateSerializer(data=data)
        serializer = BlogPostSerializer(blog_post, data=request.data)
        #data = {}
        if serializer.is_valid():

            serializer.save()
            # blog_post = serializer.save()
            #data['response'] = CREATE_SUCCESS
            # data['pk'] = blog_post.pk
            # data['title'] = blog_post.title
            # data['body'] = blog_post.body
            # data['slug'] = blog_post.slug
            # data['date_updated'] = blog_post.date_updated
            # image_url = str(request.build_absolute_uri(blog_post.image.url))
            # if "?" in image_url:
            #	image_url = image_url[:image_url.rfind("?")]
            # data['image'] = image_url
            # data['username'] = blog_post.author.username
            # return Response(data=data)
            return Response(serializer.data)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# Response: https://gist.github.com/mitchtabian/ae03573737067c9269701ea662460205
# Url:
#		1) list: https://<your-domain>/api/blog/list
#		2) pagination: http://<your-domain>/api/blog/list?page=2
#		3) search: http://<your-domain>/api/blog/list?search=mitch
#		4) ordering: http://<your-domain>/api/blog/list?ordering=-date_updated
#		4) search + pagination + ordering: <your-domain>/api/blog/list?search=mitch&page=2&ordering=-date_updated
# Headers: Authorization: Token <token>
'''
class ApiBlogListView(ListAPIView):
	queryset = BlogPost.objects.all()
	serializer_class = BlogPostSerializer
	authentication_classes = (TokenAuthentication,)
	permission_classes = (IsAuthenticated,)
	pagination_class = PageNumberPagination
	filter_backends = (SearchFilter, OrderingFilter)
	search_fields = ('title', 'body', 'author__username')
 '''

blog/templates/blog/_sidebar.html
<!-- Side Bar Widgets  -->
<div class="col-md-4">
    <div class="sidebar right">

        <!-- Widget -->
        <div class="widget">
            <h3 class="margin-top-0 margin-bottom-25">Search Blog</h3>
            <form action="{% url 'blog:post_search' %}" method="GET">
                <div class="search-blog-input">
                    <div class="input"><input class="search-field" name="q" type="text" placeholder="Type and hit enter"
                            value="" /></div>
                </div>
            </form>
            <div class="clearfix"></div>
        </div>
        <!-- Widget / End -->


        <!-- Widget -->
        <div class="widget">
            <h3>Got any questions?</h3>
            <div class="info-box margin-bottom-10">
                <p>If you are having any questions, please feel free to ask.</p>
                <a href="{% url 'front:contact' %}" class="button fullwidth margin-top-20"><i
                        class="fa fa-envelope-o"></i> Drop Us a Line</a>
            </div>
        </div>
        <!-- Widget / End -->


        <!-- Widget -->
        <div class="widget">

            <h3>Popular Posts</h3>
            <ul class="widget-tabs">

                {% for latest in post_latest %}

                <!-- Post #1 -->
                <li>
                    <div class="widget-content">
                        <div class="widget-thumb">
                            <a href="{{ latest.get_absolute_url }}"><img src="{{ latest.thumbnail.url }}" alt=""></a>
                        </div>

                        <div class="widget-text">
                            <h5><a href="{{ latest.get_absolute_url }}">{{ latest.title|truncatechars:35}}</a>
                            </h5>

                            <span><i class="fa fa-eye"></i> {{ latest.view_count}} |
                                <i class="fa fa-comments"></i> {{ latest.comments.count}} </span>

                            <div class="clearfix"></div>
                        </div>
                </li>
                {% endfor %}


            </ul>

        </div>
        <!-- Widget / End-->


        <!-- Widget -->
        <div class="widget margin-bottom-40">
            <h3 class="margin-top-0 margin-bottom-35">All Post Categories</h3>

            <!-- Row Categories -->
            <div class="row with-forms">
                {% for cat in category_count %}
                <!-- Status -->
                <div class="col-md-12">
                    <a href="#" class="button fullwidth border">{{ cat.categories__title }}
                        <span>({{ cat.categories__title__count }})</span></a>
                </div>
                {% endfor %}
            </div>
            <!-- Row / End -->
        </div>
        <!-- Widget / End -->



        <!-- Widget -->
        <div class="widget">
            <h3 class="margin-top-0 margin-bottom-25">Social</h3>
            <ul class="social-icons rounded">
                <li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
                <li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
                <li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
                <li><a class="linkedin" href="#"><i class="icon-linkedin"></i></a></li>
            </ul>

        </div>
        <!-- Widget / End-->

        <div class="clearfix"></div>
        <div class="margin-bottom-40"></div>
    </div>
</div>
<!-- Sidebar / End -->

blog/templates/blog/_sidebar_user_post.html
<!-- Widget -->
<div class="col-md-4">
    <div class="sidebar left">

        <div class="my-account-nav-container">

            <ul class="my-account-nav">
                <li class="sub-nav-title">Manage Account</li>
                <li><a href="{% url 'user_profile' %}"><i class="sl sl-icon-user"></i> My Profile</a></li>
                <li><a href="my-bookmarks.html"><i class="sl sl-icon-star"></i> Bookmarked Listings</a></li>
            </ul>

            <ul class="my-account-nav">
                <li class="sub-nav-title">Manage Listings</li>
                <li><a href="{% url 'property:user_property' %}" class="current"><i class="sl sl-icon-docs"></i> My
                        Properties</a></li>
                <li><a href="{% url 'blog:user_post' %}"><i class="sl sl-icon-action-redo"></i> My Posts
                    </a></li>
                <li><a href="submit-property.html"><i class="sl sl-icon-action-redo"></i> Submit New
                        Property</a></li>
            </ul>

            <ul class="my-account-nav">
                <li><a href="change-password.html"><i class="sl sl-icon-lock"></i> Change Password</a></li>

                <li>
                    <a href="javascript:{document.getElementById('logout').submit()}">
                        <i class="sl sl-icon-power"></i> Log Out</a>
                    </a>
                    <form action="{% url 'logout' %}" method="POST" id="logout">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                </li>
            </ul>

        </div>

    </div>
</div>

blog/templates/blog/my-post.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- Titlebar
================================================== -->
<div id="titlebar">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <h2>My Posts</h2>

                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul>
                        <li><a href="{% url 'user_profile' %}">My Profile</a></li>
                        <li>My Posts</li>
                    </ul>
                </nav>

            </div>
        </div>
    </div>
</div>


<!-- Content
================================================== -->
<div class="container">
    <div class="row">


        <!-- Sidebar Widgets -->
        {%  include 'blog/_sidebar_user_post.html' %}
        <!-- Sidebar / End -->

        <div class="col-md-8">
            <a href="{% url 'blog:post_create' %}" class="margin-bottom-30 button border">Create Post</a>
            <table class="manage-table responsive-table">

                <tr>
                    <th><i class="fa fa-file-text"></i> Posts</th>
                    <th class="expire-date"><i class="fa fa-calendar"></i> Post Date</th>
                    <th>Action</th>
                </tr>

                <!-- Item #1 -->
                {% for post in post_list %}
                <tr>
                    <td class="title-container">
                        <img src="{{ post.thumbnail.url }}" alt="">
                        <div class="title">
                            <h4><a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:30}}</a></h4>
                            <span>{{ post.overview|truncatechars:20}} </span>
                            <span class="table-property-price">By: {{ post.author.user.username }} </span>
                        </div>
                    </td>
                    <td class="expire-date">{{ post.timestamp|date:'F d, Y'}}</td>
                    {% if request.user.is_staff %}
                    <td class="action">
                        <a href="{{ post.get_absolute_url }}"><i class="fa  fa-eye"></i> View</a>
                        <a href="{% url 'blog:post_update' slug=post.slug %}"><i class="fa fa-pencil"></i> Edit</a>
                        <a href="{% url 'blog:post_delete' slug=post.slug  %}" class="delete"><i
                                class="fa fa-remove"></i>
                            Delete</a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}


            </table>
            <a href="{% url 'blog:post_create' %}" class="margin-top-40 button">Create Post</a>
        </div>



    </div>
</div>

{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- Titlebar
================================================== -->
<div id="titlebar">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <h2>Blog</h2>
                <span>Keep up to date with the latest news</span>

                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li>Blog</li>
                    </ul>
                </nav>

            </div>
        </div>
    </div>
</div>


<!-- Content
================================================== -->
<div class="container">

    <!-- Blog Posts -->
    <div class="blog-page">
        <div class="row">
            <div class="col-md-8">

                {% for post in post_list %}

                <!-- Blog Post -->
                <div class="blog-post">

                    <!-- Img -->
                    <a href="{{ post.get_absolute_url }}" class="post-img">
                        <img src="{{ post.thumbnail.url }}" alt="">
                    </a>

                    <!-- Content -->
                    <div class="post-content">
                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title}}</a></h3>


                        <ul class="post-meta">
                            <li> <i class="fa fa-user"></i> {{ post.author.user.username }}</li>
                            <li> <i class="fa fa-clock-o"></i> {{ post.timestamp|naturaltime}}</li>
                            <li> <i class="fa fa-comments"></i><a href="#"> {{ post.comments.count}}</a></li>
                            <i class="fa fa-list-alt"></i>
                            {% for cat in post.categories.all %}
                            <li> </i><a href="#"> {{ cat }}</a></li>
                            {% endfor %}
                        </ul>

                        <p>{{ post.overview|truncatechars:255}}</p>

                        <a href="{{ post.get_absolute_url }}" class="read-more">Read More <i
                                class="fa fa-angle-right"></i></a>
                    </div>

                </div>
                <!-- Blog Post / End -->
                {% endfor %}

                <!-- Pagination -->
                <div class="clearfix"></div>
                {% if post_list.has_other_pages %}
                <!-- Pagination -->
                <div class="pagination-container">


                    <nav class="pagination">
                        <ul>
                            {% for i in post_list.paginator.page_range %}
                            {% if post_list.number == i %}
                            <li><a class="current-page">{{i}}</a></li>
                            {% else %}
                            <li><a href="?{{ page_request_var }}={{i}}">{{i}}</a></li>
                            {% comment %}
                            <li class="blank">...</li>
                            <li><a href="?{{ page_request_var }}={{i.previous_page_number }}">22</a></li>
                            {% endcomment %}
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </nav>

                    <nav class="pagination-next-prev">
                        <ul>
                            {% if post_list.has_previous %}
                            <li><a href="?{{ page_request_var }}={{ post_list.previous_page_number }}"
                                    class="prev">Previous</a></li>
                            {% else %}
                            <li class="disabled"></li>
                            {% endif %}

                            {% if post_list.has_next %}
                            <li><a href="?{{ page_request_var }}={{ post_list.next_page_number }}" class="next">Next</a>
                            </li>
                            {% else %}
                            <li class="disabled"></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <!-- Pagination / End -->
                {% endif %}
                <div class="clearfix"></div>

            </div>
            <!-- class="col-md-8 / end -->

            <!-- Side Bar Widgets  -->
            {%  include 'blog/_sidebar.html' with category_count=category_count post_latest=post_latest %}
            <!-- Sidebar / End -->

        </div>
        <!-- class row / End -->


    </div>
    <!-- Blog Posts / End -->
</div>
<!-- Container/ End -->



{% endblock %}

blog/templates/blog/post_create.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<!-- Titlebar
================================================== -->
<div id="titlebar">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <h2>My Profile</h2>

                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li>My Profile</li>
                    </ul>
                </nav>

            </div>
        </div>
    </div>
</div>


<!-- Content
================================================== -->
<div class="container">



    <!-- Widget -->


    <div class="col-md-6 col-md-offset-3">


        <h4 class="margin-top-0 margin-bottom-30">Create Post</h4>
        {{ form.media }}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="button margin-top-20 margin-bottom-20">Create
            </button>
        </form>



    </div>


</div>


{% endblock %}